# Generated by Django 6.0.3 on 2026-03-29 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='chapters_covered',
            field=models.ManyToManyField(blank=True, to='quiz.chapter'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='difficulty',
            field=models.CharField(default='Medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.subject'),
        ),
    ]
