# Generated by Django 5.2.3 on 2026-03-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_testresult_chapters_covered_testresult_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='questions_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='user_answers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='questionlog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
